### ISSUE TITLE
Dependency on idna-uts46 causing transpiling problems for browser

### ISSUE THREAD

**Issue by pointtoken** [danfinlay/eth-ens-namehash#5]
It seems the issue raised by @arachnid here https://github.com/jcranmer/idna-uts46/issues/5 affects this library -- we can't transpile when using webpack and uglify.

**Comment by manosamy** [comment]
I forked this library, and made it to use [idna-uts46](https://github.com/hexonet/idna-uts46), also changed one more line to downgrade from ES6 to ES5, published to npm as eth-ens-namehash-ms
So that I can uglify without errors

**Comment by danfinlay** [comment]
Fixed by #7.
