### ISSUE TITLE
suggestion: normalize() doesn't eliminate phishing risk, please state so explicitly in readme

### ISSUE THREAD

**Issue by manosamy** [danfinlay/eth-ens-namehash#6]
faceboоk.eth
facebook.eth
The first one has non-ascii chars. (control+F on this page and search for facebook, only the second one will match).
namehash.normalize() doesn't automagically remap those, it doesn't claim to, but stating it explicitly in documentation would help prevent anyone making bad assumptions.

**Comment by danfinlay** [comment]
Fixed by https://github.com/danfinlay/eth-ens-namehash/commit/ca945b3bfdc0dea6ba36d7c5d0d5506e093f7da0
